print("Program nama/biodata")
print("silahkan isi data-data berikut :")
fullname = input("Nama Lengkap : ")
nickname = input("Nama Panggilan : ")
bdp = input("Tempat,Tanggal lahir : ")
addr = input("Alamat : ")
hobby = input("Hobi : ")

print("Biodata Anda Sebagai Berikut ")
print("Nama Lengkap         : ",fullname)
print("Nama Panggilan       : ",nickname)
print("Tempat,Tanggal Lahir : ",bdp)
print("Alamat               : ",addr)
print("Hobi                 : ",hobby)